name: Debug build
run-name: Menu template build
on:
  push: 
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: 
    inputs: 
      job_target:
        description: 'Select the platform'
        required: true
        default: 'Both'
        type: choice
        options:
          - Linux
          - Windows
          - Both
          
env:
  GODOT_VERSION: 4.4.1
  GODOT_PROJECT_LOCATION: project.godot
  EXPORT_FOLDER_LINUX: bin/linux
  EXPORT_FOLDER_WINDOWS: bin/windows
  APPLICATION_NAME: Menu_Template
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Settings extra variables
        run:
          export DATE=$(date +'%Y-%m-%d')
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "MAIN_FOLDER=$(pwd)" >> $GITHUB_ENV
          echo "JOB_TARGET='Both'" >> $GITHUB_ENV

      - name: Debug job target
        run: echo ${{ env.JOB_TARGET }}
        
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 fontconfig

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive    

      - name: Prepare Godot
        run: |
          wget -q -O godot_linux.zip https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION}}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          unzip godot_linux.zip
          wget -q -O godot_export_templates.tpz https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          unzip godot_export_templates.tpz -d ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          mv ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable/templates/* ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable

      - name: Building debug Windows
        run: |
          mkdir -p ${{ env.EXPORT_FOLDER_WINDOWS }}
          ./Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 --import ${{ env.GODOT_PROJECT_LOCATION }} --quiet --headless --export-debug Windows ${{ env.MAIN_FOLDER }}/${{ env.EXPORT_FOLDER_WINDOWS }}/${{ env.APPLICATION_NAME }}.exe

      - name: Uploading GDExtension Windows artifact debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPLICATION_NAME }}_windows_debug_$${{ env.DATE }}
          path: ${{ env.EXPORT_FOLDER_WINDOWS }}/


